script_args = {
    'academic_advising': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'num_levels', 'type': int, 'min': 1, 'max': 5},
        {'param_name': 'num_courses_per_level', 'type': int, 'min': 1, 'max': 5},
        {'param_name': 'num_prereqs', 'type': int, 'min': 1, 'max': 5},
        {'param_name': 'prob_more_less_prereqs', 'type': float, 'min': 0.0, 'max': 1.0},
        {'param_name': 'prob_prog_req', 'type': float, 'min': 0.0, 'max': 1.0},
        {'param_name': 'num_conc_actions', 'type': int, 'min': 1, 'max': 1},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    # 'academic_advising': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'num_levels', 'type': int, 'min': 5, 'max': 8},
    #     {'param_name': 'num_courses_per_level', 'type': int, 'min': 5, 'max': 8},
    #     {'param_name': 'num_prereqs', 'type': int, 'min': 1, 'max': 5},
    #     {'param_name': 'prob_more_less_prereqs', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'prob_prog_req', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'num_conc_actions', 'type': int, 'min': 1, 'max': 1},
    #     {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    # 'academic_advising': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'num_levels', 'type': int, 'min': 10, 'max': 12},
    #     {'param_name': 'num_courses_per_level', 'type': int, 'min': 6, 'max': 10},
    #     {'param_name': 'num_prereqs', 'type': int, 'min': 1, 'max': 5},
    #     {'param_name': 'prob_more_less_prereqs', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'prob_prog_req', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'num_conc_actions', 'type': int, 'min': 1, 'max': 1},
    #     {'param_name': 'horizon', 'type': int, 'min': 60, 'max': 60},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    # 'academic_advising_chain': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'num_levels', 'type': int, 'min': 2, 'max': 8},
    #     {'param_name': 'num_courses_per_level', 'type': int, 'min': 2, 'max': 8},
    #     {'param_name': 'num_prereqs', 'type': int, 'min': 1, 'max': 1},
    #     {'param_name': 'prob_more_less_prereqs', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'num_reqs', 'type': int, 'min': 1, 'max': 4},
    #     {'param_name': 'num_conc_actions', 'type': int, 'min': 1, 'max': 1},
    #     {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ], TRAIN
    # 'academic_advising_chain': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'num_levels', 'type': int, 'min': 7, 'max': 12},
    #     {'param_name': 'num_courses_per_level', 'type': int, 'min': 3, 'max': 8},
    #     {'param_name': 'num_prereqs', 'type': int, 'min': 1, 'max': 1},
    #     {'param_name': 'prob_more_less_prereqs', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'num_reqs', 'type': int, 'min': 1, 'max': 4},
    #     {'param_name': 'num_conc_actions', 'type': int, 'min': 1, 'max': 1},
    #     {'param_name': 'horizon', 'type': int, 'min': 100, 'max': 100},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ], VAL
    # 'academic_advising_chain': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'num_levels', 'type': int, 'min': 12, 'max': 20},
    #    {'param_name': 'num_courses_per_level', 'type': int, 'min': 5, 'max': 8},
    #    {'param_name': 'num_prereqs', 'type': int, 'min': 1, 'max': 1},
    #    {'param_name': 'prob_more_less_prereqs', 'type': float, 'min': 0.0, 'max': 1.0},
    #    {'param_name': 'num_reqs', 'type': int, 'min': 1, 'max': 4},
    #    {'param_name': 'num_conc_actions', 'type': int, 'min': 1, 'max': 1},
    #    {'param_name': 'horizon', 'type': int, 'min': 200, 'max': 200},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    'academic_advising_prob': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'num_levels', 'type': int, 'min': 2, 'max': 8},
        {'param_name': 'num_courses_per_level', 'type': int, 'min': 2, 'max': 8},
        {'param_name': 'num_prereqs', 'type': int, 'min': 1, 'max': 1},
        {'param_name': 'prob_more_less_prereqs', 'type': float, 'min': 0.0, 'max': 1.0},
        {'param_name': 'num_reqs', 'type': int, 'min': 1, 'max': 4},
        {'param_name': 'num_conc_actions', 'type': int, 'min': 1, 'max': 1},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    # 'academic_advising_prob': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'num_levels', 'type': int, 'min': 7, 'max': 12},
    #     {'param_name': 'num_courses_per_level', 'type': int, 'min': 3, 'max': 8},
    #     {'param_name': 'num_prereqs', 'type': int, 'min': 1, 'max': 1},
    #     {'param_name': 'prob_more_less_prereqs', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'num_reqs', 'type': int, 'min': 1, 'max': 4},
    #     {'param_name': 'num_conc_actions', 'type': int, 'min': 1, 'max': 1},
    #     {'param_name': 'horizon', 'type': int, 'min': 100, 'max': 100},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ], VAL
    # 'academic_advising_chain': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'num_levels', 'type': int, 'min': 12, 'max': 20},
    #    {'param_name': 'num_courses_per_level', 'type': int, 'min': 5, 'max': 8},
    #    {'param_name': 'num_prereqs', 'type': int, 'min': 1, 'max': 1},
    #    {'param_name': 'prob_more_less_prereqs', 'type': float, 'min': 0.0, 'max': 1.0},
    #    {'param_name': 'num_reqs', 'type': int, 'min': 1, 'max': 4},
    #    {'param_name': 'num_conc_actions', 'type': int, 'min': 1, 'max': 1},
    #    {'param_name': 'horizon', 'type': int, 'min': 200, 'max': 200},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    # 'pizza_delivery': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'width', 'type': int, 'min': 5, 'max': 12},
    #     {'param_name': 'height', 'type': int, 'min': 5, 'max': 12},
    #     {'param_name': 'num_goals', 'type': int, 'min': 2, 'max': 4},
    #     {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ], TRAIN
    # 'pizza_delivery': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'width', 'type': int, 'min': 10, 'max': 15},
    #     {'param_name': 'height', 'type': int, 'min': 10, 'max': 15},
    #     {'param_name': 'num_goals', 'type': int, 'min': 2, 'max': 4},
    #     {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    'pizza_delivery': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'width', 'type': int, 'min': 15, 'max': 20},
        {'param_name': 'height', 'type': int, 'min': 15, 'max': 20},
        {'param_name': 'num_goals', 'type': int, 'min': 2, 'max': 4},
        {'param_name': 'horizon', 'type': int, 'min': 80, 'max': 80},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    # 'pizza_delivery_grid': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'width', 'type': int, 'min': 5, 'max': 12},
    #     {'param_name': 'height', 'type': int, 'min': 5, 'max': 12},
    #     {'param_name': 'num_goals', 'type': int, 'min': 2, 'max': 4},
    #     {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ], TRAIN
    # 'pizza_delivery_grid': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'width', 'type': int, 'min': 13, 'max': 16},
    #     {'param_name': 'height', 'type': int, 'min': 13, 'max': 16},
    #     {'param_name': 'num_goals', 'type': int, 'min': 2, 'max': 4},
    #     {'param_name': 'horizon', 'type': int, 'min': 50, 'max': 50},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ], VAL
    'pizza_delivery_grid': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'width', 'type': int, 'min': 20, 'max': 22},
        {'param_name': 'height', 'type': int, 'min': 20, 'max': 22},
        {'param_name': 'num_goals', 'type': int, 'min': 2, 'max': 4},
        {'param_name': 'horizon', 'type': int, 'min': 80, 'max': 80},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    'pizza_delivery_windy': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'width', 'type': int, 'min': 5, 'max': 12},
        {'param_name': 'height', 'type': int, 'min': 5, 'max': 12},
        {'param_name': 'num_goals', 'type': int, 'min': 2, 'max': 4},
        {'param_name': 'horizon', 'type': int, 'min': 100, 'max': 100},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ], 
    # 'pizza_delivery_windy': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'width', 'type': int, 'min': 14, 'max': 16},
    #     {'param_name': 'height', 'type': int, 'min': 14, 'max': 16},
    #     {'param_name': 'num_goals', 'type': int, 'min': 2, 'max': 4},
    #     {'param_name': 'horizon', 'type': int, 'min': 150, 'max': 150},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ], VAL
    # 'pizza_delivery_windy': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'width', 'type': int, 'min': 20, 'max': 22},
    #     {'param_name': 'height', 'type': int, 'min': 20, 'max': 22},
    #    {'param_name': 'num_goals', 'type': int, 'min': 2, 'max': 4},
    #    {'param_name': 'horizon', 'type': int, 'min': 200, 'max': 200},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    'crossing_traffic': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'size_x', 'type': int, 'min': 3, 'max': 7},
        {'param_name': 'size_y', 'type': int, 'min': 3, 'max': 7},
        {'param_name': 'input_rate', 'type': float, 'min': 0.0, 'max': 0.2},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    #'crossing_traffic': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'size_x', 'type': int, 'min': 8, 'max': 10},
    #    {'param_name': 'size_y', 'type': int, 'min': 8, 'max': 10},
    #    {'param_name': 'input_rate', 'type': float, 'min': 0.0, 'max': 0.2},
    #    {'param_name': 'horizon', 'type': int, 'min': 80, 'max': 80},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    #'crossing_traffic': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'size_x', 'type': int, 'min': 10, 'max': 13},
    #    {'param_name': 'size_y', 'type': int, 'min': 10, 'max': 13},
    #    {'param_name': 'input_rate', 'type': float, 'min': 0.0, 'max': 0.2},
    #    {'param_name': 'horizon', 'type': int, 'min': 120, 'max': 120},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    'game_of_life': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'size_x', 'type': int, 'min': 2, 'max': 5},
        {'param_name': 'size_y', 'type': int, 'min': 2, 'max': 5},
        {'param_name': 'noise_prob_min', 'type': float, 'min': 0.0, 'max': 0.0},
        {'param_name': 'noise_prob_max', 'type': float, 'min': 1.0, 'max': 1.0},
        {'param_name': 'init_state_prob', 'type': float, 'min': 0.0, 'max': 1.0},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    # 'game_of_life': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'size_x', 'type': int, 'min': 6, 'max': 8},
    #    {'param_name': 'size_y', 'type': int, 'min': 6, 'max': 8},
    #    {'param_name': 'noise_prob_min', 'type': float, 'min': 0.1, 'max': 0.1},
    #    {'param_name': 'noise_prob_max', 'type': float, 'min': 0.1, 'max': 0.3},
    #    {'param_name': 'init_state_prob', 'type': float, 'min': 0.2, 'max': 0.5},
    #    {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #], VAL
    #'game_of_life': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'size_x', 'type': int, 'min': 9, 'max': 10},
    #    {'param_name': 'size_y', 'type': int, 'min': 9, 'max': 10},
    #    {'param_name': 'noise_prob_min', 'type': float, 'min': 0.1, 'max': 0.1},
    #    {'param_name': 'noise_prob_max', 'type': float, 'min': 0.1, 'max': 0.3},
    #    {'param_name': 'init_state_prob', 'type': float, 'min': 0.2, 'max': 0.5},
    #    {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    'skill_teaching': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'minNumSkills', 'type': int, 'min': 1, 'max': 1},
        {'param_name': 'maxNumSkills', 'type': int, 'min': 7, 'max': 7},
        {'param_name': 'maxPreReqs', 'type': int, 'min': 4, 'max': 4},
        {'param_name': 'maxMedCorrectProb', 'type': float, 'min': 0.0, 'max': 1.0},
        {'param_name': 'maxLowCorrectProb', 'type': float, 'min': 0.0, 'max': 1.0},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    #'skill_teaching': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'minNumSkills', 'type': int, 'min': 1, 'max': 1},
    #    {'param_name': 'maxNumSkills', 'type': int, 'min': 7, 'max': 7},
    #    {'param_name': 'maxPreReqs', 'type': int, 'min': 4, 'max': 4},
    #    {'param_name': 'maxMedCorrectProb', 'type': float, 'min': 0.0, 'max': 1.0},
    #    {'param_name': 'maxLowCorrectProb', 'type': float, 'min': 0.0, 'max': 1.0},
    #    {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #], VAL
    #'skill_teaching': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'minNumSkills', 'type': int, 'min': 5, 'max': 5},
    #    {'param_name': 'maxNumSkills', 'type': int, 'min': 10, 'max': 10},
    #    {'param_name': 'maxPreReqs', 'type': int, 'min': 4, 'max': 4},
    #    {'param_name': 'maxMedCorrectProb', 'type': float, 'min': 0.0, 'max': 1.0},
    #    {'param_name': 'maxLowCorrectProb', 'type': float, 'min': 0.0, 'max': 1.0},
    #    {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    'recon': [ # for small instances
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'size', 'type': int, 'min': 3, 'max': 7},
        {'param_name': 'maxObjects', 'type': int, 'min': 3, 'max': 5},
        {'param_name': 'damageProbMax', 'type': float, 'min': 0.3, 'max': 0.4},
        {'param_name': 'maxHazardDensity', 'type': float, 'min': 0.0, 'max': 0.1},
        {'param_name': 'lifeDensity', 'type': float, 'min': 0.0, 'max': 1.0},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    #'recon': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'size', 'type': int, 'min': 9, 'max': 11},
    #    {'param_name': 'maxObjects', 'type': int, 'min': 3, 'max': 5},
    #    {'param_name': 'damageProbMax', 'type': float, 'min': 0.3, 'max': 0.4},
    #    {'param_name': 'maxHazardDensity', 'type': float, 'min': 0.0, 'max': 0.1},
    #    {'param_name': 'lifeDensity', 'type': float, 'min': 0.0, 'max': 1.0},
    #    {'param_name': 'horizon', 'type': int, 'min': 60, 'max': 60},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    #'recon': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'size', 'type': int, 'min': 10, 'max': 15},
    #    {'param_name': 'maxObjects', 'type': int, 'min': 3, 'max': 5},
    #    {'param_name': 'damageProbMax', 'type': float, 'min': 0.3, 'max': 0.4},
    #    {'param_name': 'maxHazardDensity', 'type': float, 'min': 0.0, 'max': 0.1},
    #    {'param_name': 'lifeDensity', 'type': float, 'min': 0.0, 'max': 1.0},
    #    {'param_name': 'horizon', 'type': int, 'min': 100, 'max': 100},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    # 'recon': [ old config which has 
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'size', 'type': int, 'min': 12, 'max': 15},
    #     {'param_name': 'maxObjects', 'type': int, 'min': 3, 'max': 5},
    #     {'param_name': 'damageProbMax', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'maxHazardDensity', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'lifeDensity', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    #'recon': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'size', 'type': int, 'min': 15, 'max': 16},
    #     {'param_name': 'maxObjects', 'type': int, 'min': 2, 'max': 5},
    #     {'param_name': 'damageProbMax', 'type': float, 'min': 0.0, 'max': 0.5},
    #     {'param_name': 'maxHazardDensity', 'type': float, 'min': 0.0, 'max': 0.1},
    #     {'param_name': 'lifeDensity', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    # This is for recon-without-hazards-train
    #'recon': [ 
    # 	{'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'size', 'type': int, 'min': 14, 'max': 20},
    #    {'param_name': 'maxObjects', 'type': int, 'min': 2, 'max': 4},
    #    {'param_name': 'damageProbMax', 'type': float, 'min': 0.0, 'max': 0.5},
    #    {'param_name': 'maxHazardDensity', 'type': float, 'min': 0.0, 'max': 0.0},
    #    {'param_name': 'lifeDensity', 'type': float, 'min': 0.0, 'max': 1.0},
    #    {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    # These are for stochastic IPPC navigation
    # output-dir instance-name size_x size_y {obfuscate,normal} horizon discount
    'navigation': [
         {'param_name': 'output-dir', 'type': str},
         {'param_name': 'instance-name', 'type': str},
         {'param_name': 'size_x', 'type': int, 'min': 3, 'max': 7},
         {'param_name': 'size_y', 'type': int, 'min': 3, 'max': 7},
         {'param_name': 'type', 'type': str, 'value': 'normal'},
         {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
         {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    # 'navigation': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'size_x', 'type': int, 'min': 5, 'max': 10},
    #     {'param_name': 'size_y', 'type': int, 'min': 5, 'max': 10},
    #     {'param_name': 'type', 'type': str, 'value': 'normal'},
    #     {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    # 'navigation': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'size_x', 'type': int, 'min': 8, 'max': 12},
    #    {'param_name': 'size_y', 'type': int, 'min': 8, 'max': 12},
    #    {'param_name': 'type', 'type': str, 'value': 'normal'},
    #    {'param_name': 'horizon', 'type': int, 'min': 60, 'max': 60},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    # These are for deterministic navigation
    # 'navigation': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'n', 'type': int, 'min': 9, 'max': 14},
    #     {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    # 'navigation': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'n', 'type': int, 'min': 15, 'max': 18},
    #     {'param_name': 'horizon', 'type': int, 'min': 60, 'max': 60},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    # 'navigation': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'n', 'type': int, 'min': 20, 'max': 25},
    #     {'param_name': 'horizon', 'type': int, 'min': 60, 'max': 60},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    'sysadmin': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'num-comp', 'type': int, 'min': 2, 'max': 15},
        {'param_name': 'num-neighbours', 'type': int, 'min': 0, 'max': 4},
        {'param_name': 'reboot-prob', 'type': float, 'min': 0.0, 'max': 1.0},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    #'sysadmin': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'num-comp', 'type': int, 'min': 15, 'max': 25},
    #    {'param_name': 'num-neighbours', 'type': int, 'min': 0, 'max': 4},
    #    {'param_name': 'reboot-prob', 'type': float, 'min': 0.0, 'max': 1.0},
    #    {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    'traffic': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'num-cells', 'type': int, 'min': 2, 'max': 6},
        {'param_name': 'input-min', 'type': float, 'min': 0.0, 'max': 0.0},
        {'param_name': 'input-max', 'type': float, 'min': 1.0, 'max': 1.0},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    #'traffic': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'num-cells', 'type': int, 'min': 4, 'max': 8},
    #    {'param_name': 'input-min', 'type': float, 'min': 0.0, 'max': 0.0},
    #    {'param_name': 'input-max', 'type': float, 'min': 1.0, 'max': 1.0},
    #    {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    'elevators': [
    	{'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'num-elevators', 'type': int, 'min': 1, 'max': 2},
        {'param_name': 'num-floors', 'type': int, 'min': 3, 'max': 7},
        {'param_name': 'max-arrive', 'type': float, 'min': 0.15, 'max': 0.2},
        {'param_name': 'min-arrive', 'type': float, 'min': 0.05, 'max': 0.1},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    #'elevators': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'num-elevators', 'type': int, 'min': 1, 'max': 2},
    #    {'param_name': 'num-floors', 'type': int, 'min': 6, 'max': 10},
    #    {'param_name': 'max-arrive', 'type': float, 'min': 0.15, 'max': 0.2},
    #    {'param_name': 'min-arrive', 'type': float, 'min': 0.05, 'max': 0.1},
    #    {'param_name': 'horizon', 'type': int, 'min': 60, 'max': 60},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #], 
    # 'elevators': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'num-elevators', 'type': int, 'min': 1, 'max': 2},
    #    {'param_name': 'num-floors', 'type': int, 'min': 8, 'max': 14},
    #    {'param_name': 'max-arrive', 'type': float, 'min': 0.15, 'max': 0.2},
    #    {'param_name': 'min-arrive', 'type': float, 'min': 0.05, 'max': 0.1},
    #    {'param_name': 'horizon', 'type': int, 'min': 100, 'max': 100},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    'tamarisk': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'num_reaches', 'type': int, 'min': 1, 'max': 6},
        {'param_name': 'num_slots', 'type': int, 'min': 1, 'max': 4},
        {'param_name': 'prob_native', 'type': float, 'min': 0.0, 'max': 1.0},
        {'param_name': 'prob_tamarisk', 'type': float, 'min': 0.0, 'max': 1.0},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    #'tamarisk': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'num_reaches', 'type': int, 'min': 6, 'max': 8},
    #    {'param_name': 'num_slots', 'type': int, 'min': 2, 'max': 6},
    #    {'param_name': 'prob_native', 'type': float, 'min': 0.0, 'max': 1.0},
    #    {'param_name': 'prob_tamarisk', 'type': float, 'min': 0.0, 'max': 1.0},
    #    {'param_name': 'horizon', 'type': int, 'min': 60, 'max': 60},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #], VAL
    # 'tamarisk': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'num_reaches', 'type': int, 'min': 8, 'max': 10},
    #     {'param_name': 'num_slots', 'type': int, 'min': 3, 'max': 7},
    #     {'param_name': 'prob_native', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'prob_tamarisk', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    'wildfire': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'size_x', 'type': int, 'min': 3, 'max': 5},
        {'param_name': 'size_y', 'type': int, 'min': 3, 'max': 5},
        {'param_name': 'num_targets', 'type': int, 'min': 4, 'max': 10},
        {'param_name': 'prob_drop_neighbor', 'type': float, 'min': 0.0, 'max': 1.0},
        {'param_name': 'burn_prob', 'type': float, 'min': 0.0, 'max': 1.0},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    # 'wildfire': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'size_x', 'type': int, 'min': 6, 'max': 8},
    #     {'param_name': 'size_y', 'type': int, 'min': 6, 'max': 8},
    #     {'param_name': 'num_targets', 'type': int, 'min': 4, 'max': 10},
    #     {'param_name': 'prob_drop_neighbor', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'burn_prob', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    # 'wildfire': [
    #     {'param_name': 'output-dir', 'type': str},
    #     {'param_name': 'instance-name', 'type': str},
    #     {'param_name': 'size_x', 'type': int, 'min': 8, 'max': 12},
    #     {'param_name': 'size_y', 'type': int, 'min': 8, 'max': 12},
    #     {'param_name': 'num_targets', 'type': int, 'min': 4, 'max': 10},
    #     {'param_name': 'prob_drop_neighbor', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'burn_prob', 'type': float, 'min': 0.0, 'max': 1.0},
    #     {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #     {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    'wall': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'n', 'type': int, 'min': 5, 'max': 10},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    #'wall': [
    #	{'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'n', 'type': int, 'min': 11, 'max': 15},
    #    {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    #'wall': [
    #	{'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'n', 'type': int, 'min': 16, 'max': 20},
    #    {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    # ],
    'stochastic_wall': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'n', 'type': int, 'min': 5, 'max': 10},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    'stochastic_wall': [
       {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'n', 'type': int, 'min': 11, 'max': 15},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    'stochastic_wall': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'n', 'type': int, 'min': 16, 'max': 20},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    'stochastic_navigation': [
	{'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'w', 'type': int, 'min': 5, 'max': 10},
        {'param_name': 'h', 'type': int, 'min': 5, 'max': 10},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    'stochastic_navigation': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'w', 'type': int, 'min': 11, 'max': 15},
        {'param_name': 'h', 'type': int, 'min': 11, 'max': 15},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    #'stochastic_navigation': [
    #    {'param_name': 'output-dir', 'type': str},
    #    {'param_name': 'instance-name', 'type': str},
    #    {'param_name': 'w', 'type': int, 'min': 15, 'max': 20},
    #    {'param_name': 'h', 'type': int, 'min': 15, 'max': 20},
    #    {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
    #    {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    #],
    'corridor': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'w', 'type': int, 'min': 5, 'max': 10},
        {'param_name': 'h', 'type': int, 'min': 5, 'max': 10},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    'corridor': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'w', 'type': int, 'min': 11, 'max': 15},
        {'param_name': 'h', 'type': int, 'min': 11, 'max': 15},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
    'corridor': [
        {'param_name': 'output-dir', 'type': str},
        {'param_name': 'instance-name', 'type': str},
        {'param_name': 'w', 'type': int, 'min': 15, 'max': 20},
        {'param_name': 'h', 'type': int, 'min': 15, 'max': 20},
        {'param_name': 'horizon', 'type': int, 'min': 40, 'max': 40},
        {'param_name': 'discount', 'type': float, 'min': 1.0, 'max': 1.0},
    ],
}

script_name = {
    'academic_advising': 'AcademicAdvisingMDPGen',
    'crossing_traffic': 'CrossingTrafficMDPGen',
    'stochastic_navigation': 'StochasticNavigationMDPGen.py',
    'elevators': 'ElevatorMDPGen',
    'game_of_life': 'GameOfLifeMDPGen',
    # 'navigation': 'NavigationMDPGen.py',
    'navigation': 'NavigationMDPGen',
    'recon': 'ReconMDPGen',
    'wall': 'WallMDPGen.py',
    'skill_teaching': 'SkillTeachingMDPGen',
    'sysadmin': 'SysAdminMDPGen',
    'tamarisk': 'TamariskMDPGen',
    'traffic': 'TrafficMDPGen',
    'triangle_tireworld': 'TriangleTireworldMDPGen',
    'wildfire': 'WildfireMDPGen',
    'academic_advising_chain': 'AcademicAdvisingChainMDPGen.py',
    'academic_advising_prob': 'AcademicAdvisingProbMDPGen.py',
    'pizza_delivery': 'PizzaDeliveryMDPGen.py',
    'pizza_delivery_grid': 'PizzaDeliveryGridMDPGen.py',
    'pizza_delivery_windy': 'PizzaDeliveryWindyMDPGen.py',
    'stochastic_wall': 'StochasticWallMDPGen.py',
    'corridor': 'CorridorMDPGen.py'
}
